# The Docker image that will be used to build your app
image: ruby:2.7

pages:
  stage: deploy
  script:
    - echo "Deploying HTML files to GitLab Pages"
  artifacts:
    paths:
      - project
  only:
    - main